"""Learning concrete learning models (pure Python).

Models depend on no Home Assistant, storage, coordinator or other concrete model;
they consume episodes and features and produce typed predictions.
"""
from .onset_delay import (
    OnsetDelayBucket,
    OnsetDelayDiagnostics,
    OnsetDelayModel,
    OnsetDelayParameters,
    OnsetDelayPredictionContext,
    OnsetDelayRebuildItem,
    OnsetDelayRejection,
    OnsetDelaySample,
    OnsetDelayState,
    OnsetDelayUpdateContext,
    onset_delay_model_definition,
)
from .heat_rate import (
    MODEL_VERSION,
    PARAMETER_VERSION,
    HeatRateBucket,
    HeatRateDiagnostics,
    HeatRateModel,
    HeatRateParameters,
    HeatRatePredictionContext,
    HeatRateRebuildItem,
    HeatRateRejection,
    HeatRateSample,
    HeatRateState,
    HeatRateUpdateContext,
    heat_rate_model_definition,
)
from .heat_loss import (
    HeatLossBucket,
    HeatLossDiagnostics,
    HeatLossModel,
    HeatLossParameters,
    HeatLossPredictionContext,
    HeatLossRebuildItem,
    HeatLossRejection,
    HeatLossSample,
    HeatLossState,
    HeatLossUpdateContext,
    heat_loss_model_definition,
)
from .afterheat import (
    AfterheatBucket,
    AfterheatDiagnostics,
    AfterheatModel,
    AfterheatParameters,
    AfterheatPrediction,
    AfterheatPredictionContext,
    AfterheatRebuildItem,
    AfterheatRejection,
    AfterheatSample,
    AfterheatState,
    AfterheatUpdateContext,
    afterheat_model_definition,
)
from .boost import (
    EVALUATION_VERSION,
    BoostBucket,
    BoostDiagnostics,
    BoostEffect,
    BoostEvaluation,
    BoostLifecycle,
    BoostModel,
    BoostOutcomeClass,
    BoostParameters,
    BoostPredictionContext,
    BoostRebuildItem,
    BoostRecommendation,
    BoostRejection,
    BoostSample,
    BoostState,
    BoostUpdateContext,
    boost_model_definition,
    boost_offset_c_to_compat_factor,
    class_effect,
    classify_boost_outcome,
)
from .boost_reliability import (
    BoostConfounder,
    BoostDeviceDispatchEvidence,
    BoostOutcomeLifecycleState,
    BoostOutcomeReliability,
    MultiTrvParams,
    ConfounderEvaluation,
    ConfounderSeverity,
    OvershootStabilityEvidence,
    OvershootStabilityParams,
    SupplyDelayParams,
    TargetStabilityEvidence,
    TargetStabilityParams,
    adaptive_allowed,
    afterheat_attribution_severity,
    class_min_reliability,
    compute_outcome_reliability,
    early_cutoff_interaction_severity,
    evaluate_confounders,
    evaluate_multi_trv,
    evaluate_overshoot_stability,
    evaluate_target_stability,
    severity_of,
    supply_delay_confounder,
)
from .boost_activation import (
    ACTIVATION_CONTRACT_VERSION,
    MIN_ACTIVATION_CONFIDENCE,
    MIN_ACTIVATION_RELIABILITY,
    BoostActivationReadiness,
    BoostEligibilityReason,
    build_activation_readiness,
)
from .boost_degradation import (
    BoostDegradationState,
    BoostLearningReadiness,
    BoostScopedDegradation,
    DegradationParams,
    KnownGoodState,
    RollbackAction,
    ScopedObserveResult,
    classify_evidence,
    is_scope_eligible,
    maybe_capture_known_good,
    observe as observe_degradation,
    observe_scoped,
    recompute_readiness,
    resolve_cooldown,
    resolve_scoped_cooldown,
)
from .baseline_comparison import (
    BASELINE_CONTEXT_VERSION,
    BaselineComparisonStore,
    BaselineEstimate,
    BaselineParams,
    BaselineQuery,
    BaselineRejection,
    BaselineSampleRejection,
    BaselineSource,
    BaselineTimingBasis,
    NonBoostBaselineSample,
    build_non_boost_sample,
    estimate_non_boost_duration,
    similarity,
)
from .manual_correction import (
    CorrectionAttribution,
    CorrectionDirection,
    CorrectionIntent,
    CorrectionPrediction,
    CorrectionRecommendation,
    CorrectionSourceClass,
    ManualCorrectionBucket,
    ManualCorrectionDiagnostics,
    ManualCorrectionEvaluation,
    ManualCorrectionModel,
    ManualCorrectionParameters,
    ManualCorrectionPattern,
    ManualCorrectionPredictionContext,
    ManualCorrectionRebuildItem,
    ManualCorrectionRejection,
    ManualCorrectionSample,
    ManualCorrectionState,
    ManualCorrectionUpdateContext,
    manual_correction_model_definition,
)
from .forecast import (
    ForecastBucket,
    ForecastDiagnostics,
    ForecastModel,
    ForecastParameters,
    ForecastPredictionContext,
    ForecastRebuildItem,
    ForecastRejection,
    ForecastSample,
    ForecastState,
    ForecastTrustResult,
    ForecastUpdateContext,
    forecast_model_definition,
)
from .outcome import (
    SCORING_VERSION,
    DimensionStatus,
    OutcomeBucket,
    OutcomeDiagnostics,
    OutcomeDimensions,
    OutcomeEvaluation,
    OutcomeModel,
    OutcomeParameters,
    OutcomePredictionContext,
    OutcomeRebuildItem,
    OutcomeRejection,
    OutcomeSample,
    OutcomeScore,
    OutcomeState,
    OutcomeUpdateContext,
    outcome_model_definition,
)

__all__ = [
    "OnsetDelayBucket", "OnsetDelayDiagnostics", "OnsetDelayModel", "OnsetDelayParameters",
    "OnsetDelayPredictionContext", "OnsetDelayRebuildItem", "OnsetDelayRejection",
    "OnsetDelaySample", "OnsetDelayState", "OnsetDelayUpdateContext",
    "onset_delay_model_definition",
    "MODEL_VERSION", "PARAMETER_VERSION",
    "HeatRateBucket", "HeatRateDiagnostics", "HeatRateModel", "HeatRateParameters",
    "HeatRatePredictionContext", "HeatRateRebuildItem", "HeatRateRejection",
    "HeatRateSample", "HeatRateState", "HeatRateUpdateContext",
    "heat_rate_model_definition",
    "HeatLossBucket", "HeatLossDiagnostics", "HeatLossModel", "HeatLossParameters",
    "HeatLossPredictionContext", "HeatLossRebuildItem", "HeatLossRejection",
    "HeatLossSample", "HeatLossState", "HeatLossUpdateContext",
    "heat_loss_model_definition",
    "AfterheatBucket", "AfterheatDiagnostics", "AfterheatModel", "AfterheatParameters",
    "AfterheatPrediction", "AfterheatPredictionContext", "AfterheatRebuildItem",
    "AfterheatRejection", "AfterheatSample", "AfterheatState", "AfterheatUpdateContext",
    "afterheat_model_definition",
    "SCORING_VERSION", "DimensionStatus", "OutcomeBucket", "OutcomeDiagnostics",
    "OutcomeDimensions", "OutcomeEvaluation", "OutcomeModel", "OutcomeParameters",
    "OutcomePredictionContext", "OutcomeRebuildItem", "OutcomeRejection", "OutcomeSample",
    "OutcomeScore", "OutcomeState", "OutcomeUpdateContext", "outcome_model_definition",
]
